game:
  small_blind: 2
  big_blind: 3
  max_hands: 450
  max_hands_per_session: 450
  llm_call_delay: 0.25
  mcp_enabled: true           # Enable MCP system
  mcp_script_dir: "./mcp_servers"     # Path to MCP server scripts
  model_path: "D:/llm_poker_agents/src/model_objects/poker_model.h5"
  model_input_size: 423
  model_hidden_layers: [4096, 2048, 1024, 512, 256, 128, 64]



players:

  - name: "Anthropic: Opus 4.1"
    model: "anthropic/claude-opus-4.1"
    chips: 200
    use_mcp: true
    enabled: false
    color: '#CC785C'
    
  - name: "Google: Gemini 2.5 Pro"
    model: "google/gemini-2.5-pro"
    chips: 200
    use_mcp: true
    enabled: false
    color: '#DB4437'
    
  - name: "OpenAI: Gpt 5"
    model: "openai/gpt-5"
    chips: 200
    use_mcp: true
    enabled: false
    color: '#388E3C' # Open AI Green
    
  - name: "Google: Gemini 2.5 Flash"
    model: "google/gemini-2.5-flash"
    chips: 200
    use_mcp: true
    enabled: false
    color: '#DB4437'
    
  - name: "DeepSeek: v3"
    model: "deepseek/deepseek-chat"
    chips: 200
    use_mcp: true
    enabled: false
    color: '#0D28F3'
    
  - name: "OpenAI: Gpt 4o"
    model: "openai/chatgpt-4o-latest"
    chips: 200
    use_mcp: true
    enabled: true
    color: '#388E3C' # Open AI Green
    
  - name: "Meta: Llama 3.3 70B"
    model: "meta-llama/llama-3.3-70b-instruct:free"
    chips: 200
    use_mcp: true
    enabled: true
    color: '#0081FB'

  - name: "Llama 3.1 405B"
    model: "meta-llama/llama-3.1-405b-instruct:free"
    chips: 250
    use_mcp: true
    enabled: false
    color: '#0081FB'

  - name: "Claude Sonnet 4"
    model: "anthropic/claude-sonnet-4"
    chips: 250
    use_mcp: true
    enabled: false
    color: '#CC785C'

  - name: "Gpt 5"
    model: "openai/gpt-5"
    chips: 250
    use_mcp: true
    enabled: false
    color: '#388E3C' # Open AI Green
