game:
  small_blind: 1
  big_blind: 1
  max_hands: 100
  max_hands_per_session: 500
  llm_call_delay: 0.15

players:
  - name: "player 1"
    model: "openai/chatgpt-4o-latest"
    chips: 300
    enabled: true

  - name: "player 2"
    model: "openai/chatgpt-4o-latest"
    chips: 4
    enabled: true

  - name: "player 3"
    model: "openai/chatgpt-4o-latest"
    chips: 4
    enabled: true

  - name: "Llama 3.3 70B"
    model: "meta-llama/llama-3.3-70b-instruct"
    chips: 250
    enabled: false

  - name: "Claude 3.5 Sonnet"
    model: "anthropic/claude-3.5-sonnet"
    chips: 250
    enabled: false

  - name: "Claude 3 Haiku"
    model: "anthropic/claude-3-haiku"
    chips: 250
    enabled: false

  - name: "Gpt 4.1 Nano"
    model: "openai/gpt-4.1-nano"
    chips: 250
    enabled: false

  - name: "Llama 3.1 405B"
    model: "meta-llama/llama-3.1-405b-instruct:free"
    chips: 250
    enabled: false

  - name: "Claude Sonnet 4"
    model: "anthropic/claude-sonnet-4"
    chips: 250
    enabled: false

  - name: "DeepSeek 3.1"
    model: "deepseek/deepseek-chat-v3.1"
    chips: 250
    enabled: false

  - name: "Gemini 2.5 Flash"
    model: "google/gemini-2.5-flash"
    chips: 250
    enabled: false

  - name: "Gpt 5"
    model: "openai/gpt-5"
    chips: 250
    enabled: false
