game:
  small_blind: 1
  big_blind: 2
  max_hands: 1
  max_hands_per_session: 500
  llm_call_delay: 1

players:
  - name: "Claude Sonnet 4"
    model: "anthropic/claude-sonnet-4"
    chips: 250
    enabled: true

  - name: "DeepSeek 3.1"
    model: "deepseek/deepseek-chat-v3.1"
    chips: 250
    enabled: true

  - name: "Gemini 2.5 Flash"
    model: "google/gemini-2.5-flash"
    chips: 250
    enabled: true

  - name: "Gpt 5"
    model: "openai/gpt-5"
    chips: 250
    enabled: true
